# Generated by Django 5.1.2 on 2024-12-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(default='No specification available'),
        ),
    ]
