# Generated by Django 5.1.2 on 2024-12-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
    ]
