# Generated by Django 5.1.2 on 2025-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_orderitem_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
