# Generated by Django 5.1.2 on 2025-01-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_order_reference_no_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
