# Generated by Django 5.1.2 on 2025-01-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_orderitem_selected_color_orderitem_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
