# Generated by Django 5.1.2 on 2025-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_offer_referraloffer_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='starting_date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
