# Generated by Django 5.1.2 on 2025-01-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_offer_starting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReferralOffer',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
