# Generated by Django 5.1.2 on 2025-01-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_referral_offer',
            field=models.BooleanField(default=False),
        ),
    ]
