# Generated by Django 5.1.2 on 2025-03-03 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_code',
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='percentage', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('product', 'Product Offer'), ('category', 'Category Offer'), ('referral', 'Referral Offer')], max_length=100),
        ),
    ]
